variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

stages:
  - build

lint:
  stage: build
  image: mayadata/ms-buildenv:latest
  script:
    - echo 'Hey I am running the lint'
  only:
    refs: [external_pull_requests]
