variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

stages:
  - build

lint:
  stage: build
  image: mayadata/ms-buildenv:latest
  script:
    - echo 'Hey I am running the lint'
  only:
    variables:
      - $CI_PIPELINE_SOURCE == 'external_pull_request_event'
