trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo modprobe nbd
    sudo modprobe xfs
    echo 1024 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
  displayName: 'configure kernel settings'
  
- script: |
    bash <(curl https://nixos.org/nix/install)
    source ~/.nix-profile/etc/profile.d/nix.sh
  displayName: 'Setup Nix'

- script: |
      . ~/.nix-profile/etc/profile.d/nix.sh
      export CARGO=`which cargo`
      nix-shell --run '$CARGO build --all'
      nix-shell --run '$CARGO test -- --test-threads=1'
  displayName: 'Run cargo tests'

