trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo modprobe nbd
    sudo modprobe xfs
    echo 1024 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
  displayName: 'configure kernel settings'
  
- script: |
    bash <(curl https://nixos.org/nix/install)
    source ~/.nix-profile/etc/profile.d/nix.sh
    nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
    nix-channel --update
  displayName: 'Setup Nix'

- script: |
      . ~/.nix-profile/etc/profile.d/nix.sh
      nix-shell --run 'cd mayastor && sudo -E cargo test -- --test-threads=1'
  displayName: 'Run cargo tests'

