trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    modprobe nbd
    modprobe xfs
    echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
    displayName: 'configure kernel settings'
  
steps:
- script: |
    bash <(curl https://nixos.org/nix/install)
    source ~/.nix-profile/etc/profile.d/nix.sh
    nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
    nix-channel --update
    displayName: 'Setup Nix'

steps:
- script: nix-shell --run 'cd mayastor && cargo test -- --test-threads=1'
  displayName: 'Run cargo tests'

