trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  container: 
    image: mayadata/ms-buildenv:latest
    options: --privileged -v /dev:/dev -v /bin:/host/bin
    
steps:
- script: |
    ln -s /host/bin/kmod /usr/local/bin/modprobe
    sudo modprobe nbd
    sudo modprobe xfs
    echo 1024 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
  displayName: 'configure kernel settings'
  
- script: |
    nix-shell --run 'cargo build --all-targets'
  displayName: 'Build all targets'

- script: |
    nix-shell --run 'cargo build --all-targets'
  displayName: 'Build all targets'
